language: node_js

node_js:
  - "11"

branches:
  only:
    - master
    - develop

install:
  - npm install

env:
  - NODE_ENV=production

script:
  - npm lint
  - npm build
  - npm test

cache:
  directories:
    - node_modules