language: node_js

node_js:
  - "11"

branches:
  only:
    - master
    - develop

install:
  - npm install

env:
  - NODE_ENV=production

script:
  - npm run lint
  - npm run build
  - npm run test

cache:
  directories:
    - "$HOME/.npm"